### NumPyAggregateFunctions 

In [1]:
'''
The NumPy library is the core library for scientific computing in Python. It provides 
a high-performance multidimensional array object, and tools for working with these arrays.
'''

'\nThe NumPy library is the core library for scientific computing in Python. It provides \na high-performance multidimensional array object, and tools for working with these arrays.\n'

In [2]:
#import numpy library
import numpy as np
#make numpy 2D array
x=np.array([[5,6],[7,4]])
#print 2D arrays
print(x)

[[5 6]
 [7 4]]


In [3]:
print("sum " ,x.sum())#sum of all elements of an array
print("min ",x.min())#min of array elements

print("max among rows : ",x.max(axis=0))#maximum value: [max(5,7),max(6,4)]=[7,6]
print("cumsum : ",x.cumsum(axis=1))
#Cumulative sum of the elements
print("mean : ", x.mean())#mean
print("std deviation ",np.std(x))#standard deviation
print("median : ",np.median(x))
print("correl : ",np.corrcoef(x))
#Correlation coefficient

sum  22
min  4
max among rows :  [7 6]
cumsum :  [[ 5 11]
 [ 7 11]]
mean :  5.5
std deviation  1.118033988749895
median :  5.5
correl :  [[ 1. -1.]
 [-1.  1.]]


### NumPyArrayOperations 

In [4]:
'''
The NumPy library is the core library for scientific computing in Python. It provides 
a high-performance multidimensional array object, and tools for working with these arrays.
'''

'\nThe NumPy library is the core library for scientific computing in Python. It provides \na high-performance multidimensional array object, and tools for working with these arrays.\n'

In [5]:
#import numpy library
import numpy as np
#make numpy 2D array
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
#print 2D arrays
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
#Subset Operations
print("subset : ",x[1])
print("subset : ",x[1,1])

subset :  [ 6  7  8  9 10]
subset :  7


In [7]:
#Slicing Operation
print(x[0:1])
print(x[:1])
print(x[0:5,1])

[[1 2 3 4 5]]
[[1 2 3 4 5]]
[ 2  7 12]


In [8]:
#Add row in numpy array
x=np.vstack([x,np.array([9,10,11,12,13])]) 
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 9 10 11 12 13]]


In [17]:
#horizontally stacked array
x=np.array([[1,2,3],[6,7,8]])
print(x)
y=np.hstack((x,[[9,9,0],[8,8,0]]))
print(y)

[[1 2 3]
 [6 7 8]]
[[1 2 3 9 9 0]
 [6 7 8 8 8 0]]


In [11]:
x=np.append(x,np.array([1,2,3,100,200]))
print(x)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15   9  10  11
  12  13   1   2   3 100 200]
